"""replace logo keys with has_logo flag

Revision ID: f089c96ce82b
Revises: 001_initial
Create Date: 2026-03-09 14:39:14.104194

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f089c96ce82b'
down_revision: str | None = '001_initial'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('has_logo', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_column('projects', 'logo_thumbnail_key')
    op.drop_column('projects', 'logo_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('logo_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('logo_thumbnail_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('projects', 'has_logo')
    # ### end Alembic commands ###
